FROM registry.access.redhat.com/ubi9/nodejs-20:latest AS builder
USER root
WORKDIR /opt/app-root/src
COPY minigames/package*.json ./
RUN npm ci
COPY minigames/ .
RUN chown -R 1001:0 /opt/app-root/src && chmod -R g+rwX /opt/app-root/src
USER 1001
RUN npm run build

FROM registry.access.redhat.com/ubi9/nginx-124:latest
COPY frontend/index.html /opt/app-root/src/
COPY frontend/public/ /opt/app-root/src/
COPY --from=builder /opt/app-root/src/dist/ /opt/app-root/src/minigames/
COPY frontend/nginx.d/ /opt/app-root/etc/nginx.d/
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
